// v028.A — public holiday calendars.
//
// Recurring national holidays are generated by rule here, so no yearly
// seeding is needed. Gazetted one-offs (elections, inaugurations) and any
// corrections live in the platform `public_holidays` table; each tenant can
// add its own closures in `tenant_holidays`.

import { and, eq, gte, lte, or, isNull } from 'drizzle-orm';
import type { NodePgDatabase } from 'drizzle-orm/node-postgres';
import * as schema from '../../../db/schema';
import { publicHolidays, tenantHolidays } from '../../../db/schema';
import { addDays, ISODate, toISO, weekdayIndex } from './dates';

type Tx = NodePgDatabase<typeof schema>;

export interface Holiday {
  date: ISODate;
  name: string;
  isPaid: boolean;
  source: 'NATIONAL' | 'GAZETTED' | 'COMPANY';
  id?: string;
}

/** Western Easter Sunday (anonymous Gregorian algorithm). */
export function easterSunday(year: number): ISODate {
  const a = year % 19;
  const b = Math.floor(year / 100);
  const c = year % 100;
  const d = Math.floor(b / 4);
  const e = b % 4;
  const f = Math.floor((b + 8) / 25);
  const g = Math.floor((b - f + 1) / 3);
  const h = (19 * a + b - d - g + 15) % 30;
  const i = Math.floor(c / 4);
  const k = c % 4;
  const l = (32 + 2 * e + 2 * i - h - k) % 7;
  const m = Math.floor((a + 11 * h + 22 * l) / 451);
  const month = Math.floor((h + l - 7 * m + 114) / 31);
  const day = ((h + l - 7 * m + 114) % 31) + 1;
  return toISO(new Date(Date.UTC(year, month - 1, day)));
}

function firstMonday(year: number, monthIndex0: number): ISODate {
  let d = toISO(new Date(Date.UTC(year, monthIndex0, 1)));
  while (weekdayIndex(d) !== 0) d = addDays(d, 1);
  return d;
}

/** Zambia — Public Holidays Act. A holiday falling on a Sunday is observed
 *  on the following Monday. Kenneth Kaunda Day (28 Apr) from 2022. */
export function zambiaHolidays(year: number): Holiday[] {
  const easter = easterSunday(year);
  const heroes = firstMonday(year, 6);
  const fixed: Array<[string, string]> = [
    [`${year}-01-01`, "New Year's Day"],
    [`${year}-03-08`, "International Women's Day"],
    [`${year}-03-12`, 'Youth Day'],
    [addDays(easter, -2), 'Good Friday'],
    [addDays(easter, -1), 'Holy Saturday'],
    [addDays(easter, 1), 'Easter Monday'],
    ...(year >= 2022 ? ([[`${year}-04-28`, 'Kenneth Kaunda Day']] as Array<[string, string]>) : []),
    [`${year}-05-01`, 'Labour Day'],
    [`${year}-05-25`, 'Africa Freedom Day'],
    [heroes, "Heroes' Day"],
    [addDays(heroes, 1), 'Unity Day'],
    [firstMonday(year, 7), "Farmers' Day"],
    [`${year}-10-18`, 'National Day of Prayer'],
    [`${year}-10-24`, 'Independence Day'],
    [`${year}-12-25`, 'Christmas Day'],
  ];
  const out: Holiday[] = [];
  const taken = new Set(fixed.map(([d]) => d));
  for (const [date, name] of fixed) {
    out.push({ date, name, isPaid: true, source: 'NATIONAL' });
    if (weekdayIndex(date) === 6) {
      let observed = addDays(date, 1);
      while (taken.has(observed)) observed = addDays(observed, 1);
      taken.add(observed);
      out.push({ date: observed, name: `${name} (observed)`, isPaid: true, source: 'NATIONAL' });
    }
  }
  return out;
}

/** v028.C — Malawi. Public Holidays Act: a holiday that falls on a
 *  non-working day (Saturday or Sunday) is observed on the next working day,
 *  skipping any other holiday already on it (so Christmas on a Saturday and
 *  Boxing Day on a Sunday become Monday and Tuesday). Eid al-Fitr depends on
 *  the moon and is added each year as a gazetted holiday (public_holidays)
 *  or by the organisation under Settings → Leave → Public holidays. */
export function malawiHolidays(year: number): Holiday[] {
  const easter = easterSunday(year);
  const fixed: Array<[string, string]> = [
    [`${year}-01-01`, "New Year's Day"],
    [`${year}-01-15`, 'John Chilembwe Day'],
    [`${year}-03-03`, "Martyrs' Day"],
    [addDays(easter, -2), 'Good Friday'],
    [addDays(easter, 1), 'Easter Monday'],
    [`${year}-05-01`, 'Labour Day'],
    [`${year}-05-14`, 'Kamuzu Day'],
    [`${year}-07-06`, 'Independence Day'],
    [`${year}-10-15`, "Mother's Day"],
    [`${year}-12-25`, 'Christmas Day'],
    [`${year}-12-26`, 'Boxing Day'],
  ];
  const out: Holiday[] = [];
  const taken = new Set(fixed.map(([d]) => d));
  const isWeekend = (d: string) => weekdayIndex(d) >= 5;
  for (const [date, name] of fixed) {
    out.push({ date, name, isPaid: true, source: 'NATIONAL' });
    if (isWeekend(date)) {
      let observed = addDays(date, 1);
      while (isWeekend(observed) || taken.has(observed)) observed = addDays(observed, 1);
      taken.add(observed);
      out.push({ date: observed, name: `${name} (observed)`, isPaid: true, source: 'NATIONAL' });
    }
  }
  return out;
}

/** Adds each holiday, and for one falling on a Saturday or Sunday an
 *  observed day on the next weekday not already a holiday (cascading, so
 *  Christmas and Boxing Day on a weekend become Monday and Tuesday). Names in
 *  `noSubstitute` are never moved. */
function withWeekendRule(fixed: Array<[string, string]>, noSubstitute: string[] = []): Holiday[] {
  const out: Holiday[] = [];
  const taken = new Set(fixed.map(([d]) => d));
  const isWeekend = (d: string) => weekdayIndex(d) >= 5;
  for (const [date, name] of fixed) {
    out.push({ date, name, isPaid: true, source: 'NATIONAL' });
    if (isWeekend(date) && !noSubstitute.includes(name)) {
      let observed = addDays(date, 1);
      while (isWeekend(observed) || taken.has(observed)) observed = addDays(observed, 1);
      taken.add(observed);
      out.push({ date: observed, name: `${name} (observed)`, isPaid: true, source: 'NATIONAL' });
    }
  }
  return out;
}

function nthWeekday(year: number, monthIndex0: number, weekday: number, n: number): ISODate {
  let d = toISO(new Date(Date.UTC(year, monthIndex0, 1)));
  while (weekdayIndex(d) !== weekday) d = addDays(d, 1);
  return addDays(d, 7 * (n - 1));
}

// Te Kāhui o Matariki Public Holiday Act 2022, Schedule 1 (the Friday
// closest to the Tangaroa lunar period in Pipiri).
const MATARIKI: Record<number, string> = {
  2022: '06-24', 2023: '07-14', 2024: '06-28', 2025: '06-20', 2026: '07-10', 2027: '06-25', 2028: '07-14',
  2029: '07-06', 2030: '06-21', 2031: '07-11', 2032: '07-02', 2033: '06-24', 2034: '07-07', 2035: '06-29',
  2036: '07-18', 2037: '07-10', 2038: '06-25', 2039: '07-15', 2040: '07-06', 2041: '07-19', 2042: '07-11',
  2043: '07-03', 2044: '06-24', 2045: '07-07', 2046: '06-29', 2047: '07-19', 2048: '07-03', 2049: '06-25',
  2050: '07-15', 2051: '06-30', 2052: '06-21',
};

/** v028.D — New Zealand, Holidays Act 2003 ss.44–45A. New Year's Day,
 *  2 January, Waitangi Day, ANZAC Day, Christmas and Boxing Day falling on a
 *  weekend are "Mondayised". Regional anniversary days differ by province —
 *  add yours under Settings → Leave → Public holidays. */
export function newZealandHolidays(year: number): Holiday[] {
  const easter = easterSunday(year);
  const fixed: Array<[string, string]> = [
    [`${year}-01-01`, "New Year's Day"],
    [`${year}-01-02`, "Day after New Year's Day"],
    [`${year}-02-06`, 'Waitangi Day'],
    [addDays(easter, -2), 'Good Friday'],
    [addDays(easter, 1), 'Easter Monday'],
    [`${year}-04-25`, 'ANZAC Day'],
    [nthWeekday(year, 5, 0, 1), "King's Birthday"],
    ...(MATARIKI[year] ? ([[`${year}-${MATARIKI[year]}`, 'Matariki']] as Array<[string, string]>) : []),
    [nthWeekday(year, 9, 0, 4), 'Labour Day'],
    [`${year}-12-25`, 'Christmas Day'],
    [`${year}-12-26`, 'Boxing Day'],
  ];
  return withWeekendRule(fixed);
}

/** v028.D — Australia, the holidays common to every state and territory
 *  (Fair Work Act s.115): New Year's Day, Australia Day and Christmas/Boxing
 *  Day move to the next weekday when they fall on a weekend; ANZAC Day does
 *  not move. King's Birthday is the second Monday in June everywhere except
 *  WA and Queensland. State holidays (Labour Day, Melbourne Cup, Easter
 *  Saturday …) differ — add yours under Settings → Leave → Public holidays. */
export function australiaHolidays(year: number): Holiday[] {
  const easter = easterSunday(year);
  const fixed: Array<[string, string]> = [
    [`${year}-01-01`, "New Year's Day"],
    [`${year}-01-26`, 'Australia Day'],
    [addDays(easter, -2), 'Good Friday'],
    [addDays(easter, 1), 'Easter Monday'],
    [`${year}-04-25`, 'ANZAC Day'],
    [nthWeekday(year, 5, 0, 2), "King's Birthday"],
    [`${year}-12-25`, 'Christmas Day'],
    [`${year}-12-26`, 'Boxing Day'],
  ];
  return withWeekendRule(fixed, ['ANZAC Day']);
}

/** A holiday falling on a Sunday is observed on the Monday (or the next day
 *  that isn't already a holiday). Saturdays are not moved. */
function withSundayRule(fixed: Array<[string, string]>): Holiday[] {
  const out: Holiday[] = [];
  const taken = new Set(fixed.map(([d]) => d));
  for (const [date, name] of fixed) {
    out.push({ date, name, isPaid: true, source: 'NATIONAL' });
    if (weekdayIndex(date) === 6) {
      let observed = addDays(date, 1);
      while (taken.has(observed)) observed = addDays(observed, 1);
      taken.add(observed);
      out.push({ date: observed, name: `${name} (observed)`, isPaid: true, source: 'NATIONAL' });
    }
  }
  return out;
}

/** v028.E — South Africa, Public Holidays Act 36 of 1994 (s.2(1): a
 *  holiday on a Sunday is observed on the Monday). One-off days (elections)
 *  go in public_holidays. */
export function southAfricaHolidays(year: number): Holiday[] {
  const easter = easterSunday(year);
  return withSundayRule([
    [`${year}-01-01`, "New Year's Day"],
    [`${year}-03-21`, 'Human Rights Day'],
    [addDays(easter, -2), 'Good Friday'],
    [addDays(easter, 1), 'Family Day'],
    [`${year}-04-27`, 'Freedom Day'],
    [`${year}-05-01`, "Workers' Day"],
    [`${year}-06-16`, 'Youth Day'],
    [`${year}-08-09`, "National Women's Day"],
    [`${year}-09-24`, 'Heritage Day'],
    [`${year}-12-16`, 'Day of Reconciliation'],
    [`${year}-12-25`, 'Christmas Day'],
    [`${year}-12-26`, 'Day of Goodwill'],
  ]);
}

/** v028.E — Zimbabwe, Public Holidays and Prohibition of Business Act
 *  [Chapter 10:21]: a holiday on a Sunday is observed on the Monday. Heroes'
 *  Day is the second Monday in August and Defence Forces Day the Tuesday
 *  after it. */
export function zimbabweHolidays(year: number): Holiday[] {
  const easter = easterSunday(year);
  let heroes = toISO(new Date(Date.UTC(year, 7, 1)));
  while (weekdayIndex(heroes) !== 0) heroes = addDays(heroes, 1);
  heroes = addDays(heroes, 7);
  return withSundayRule([
    [`${year}-01-01`, "New Year's Day"],
    ...(year >= 2018 ? ([[`${year}-02-21`, 'Robert Gabriel Mugabe National Youth Day']] as Array<[string, string]>) : []),
    [addDays(easter, -2), 'Good Friday'],
    [addDays(easter, -1), 'Easter Saturday'],
    [addDays(easter, 1), 'Easter Monday'],
    [`${year}-04-18`, 'Independence Day'],
    [`${year}-05-01`, "Workers' Day"],
    [`${year}-05-25`, 'Africa Day'],
    [heroes, "Heroes' Day"],
    [addDays(heroes, 1), 'Defence Forces Day'],
    [`${year}-12-22`, 'National Unity Day'],
    [`${year}-12-25`, 'Christmas Day'],
    [`${year}-12-26`, 'Boxing Day'],
  ]);
}

const GENERATORS: Record<string, (year: number) => Holiday[]> = {
  ZA: southAfricaHolidays,
  ZW: zimbabweHolidays,
  ZM: zambiaHolidays,
  MW: malawiHolidays,
  NZ: newZealandHolidays,
  AU: australiaHolidays,
};

export function hasNationalCalendar(countryCode: string): boolean {
  return !!GENERATORS[countryCode];
}

/** Every holiday affecting employees of `countryCode` in [from, to]. */
export async function holidaysBetween(
  tx: Tx,
  tenantId: string,
  countryCode: string,
  from: ISODate,
  to: ISODate,
): Promise<Holiday[]> {
  const byDate = new Map<string, Holiday>();
  const gen = GENERATORS[countryCode];
  if (gen) {
    for (let y = Number(from.slice(0, 4)); y <= Number(to.slice(0, 4)); y++) {
      for (const h of gen(y)) if (h.date >= from && h.date <= to) byDate.set(h.date, h);
    }
  }
  const gazetted = await tx
    .select()
    .from(publicHolidays)
    .where(and(eq(publicHolidays.countryCode, countryCode), gte(publicHolidays.holidayDate, from), lte(publicHolidays.holidayDate, to)));
  for (const g of gazetted) {
    if (g.isRemoved) byDate.delete(g.holidayDate);
    else byDate.set(g.holidayDate, { date: g.holidayDate, name: g.name, isPaid: g.isPaid, source: 'GAZETTED' });
  }
  const company = await tx
    .select()
    .from(tenantHolidays)
    .where(
      and(
        eq(tenantHolidays.tenantId, tenantId),
        gte(tenantHolidays.holidayDate, from),
        lte(tenantHolidays.holidayDate, to),
        or(isNull(tenantHolidays.countryCode), eq(tenantHolidays.countryCode, countryCode)),
      ),
    );
  for (const c of company) {
    byDate.set(c.holidayDate, { date: c.holidayDate, name: c.name, isPaid: c.isPaid, source: 'COMPANY', id: c.id });
  }
  return [...byDate.values()].sort((a, b) => a.date.localeCompare(b.date));
}
