// v026.A — Support knowledge base. Every article describes the app as it
// actually behaves; update the matching article when a workflow changes.
// Menu paths are written "Settings → Employees" and button labels in quotes
// exactly as they appear on screen.

export const CATEGORIES = [
  'Getting started',
  'Signing in',
  'People',
  'Leave',
  'Timesheets',
  'Payroll',
  'Recruitment',
  'Performance & training',
  'Documents & announcements',
  'Billing & plans',
  'Privacy & security',
] as const;
export type Category = (typeof CATEGORIES)[number];

export interface Article {
  slug: string;
  category: Category;
  title: string;
  summary: string;
  /** Who can do this, e.g. "Admin" or "Admin, HR". */
  who?: string;
  steps?: string[];
  body?: string[];
  tip?: string;
  tags?: string[];
}

export const ARTICLES: Article[] = [
  // ---------------------------------------------------------------- Getting started
  {
    slug: 'getting-started-checklist',
    category: 'Getting started',
    title: 'Setting up your workspace: a first-day checklist',
    summary: 'The order that gets a new tmPro workspace ready fastest.',
    who: 'Admin',
    steps: [
      'Settings → Organization: add your organisation name, logo, address, country, currency, time zone and working hours, plus your tax, superannuation/pension and health-insurance registration numbers. Click "Save".',
      'Settings → Branches: add each office or site ("New branch").',
      'Settings → Departments: add departments, and sections inside them if you use them.',
      'Settings → Designations: add job titles and who each one reports to. This builds your Org Chart.',
      'Settings → Leave: choose your country and check the leave rules (days accrued, accrual period, carry-over).',
      'Settings → Employees: add your people one by one or import a CSV file.',
      'Give each person a login from People → (person) → Permission → "Generate Login".',
    ],
    tip: 'Payroll uses each employee\'s country to apply the right tax and statutory rules, so set the country on every employee.',
    tags: ['setup', 'onboarding', 'new account', 'configure', 'organisation', 'organization'],
  },
  {
    slug: 'roles-explained',
    category: 'Getting started',
    title: 'User roles: Employee, Supervisor, HR and Admin',
    summary: 'What each role can see and do.',
    body: [
      'Employee — sees their own profile, leave, timesheets, payslips, goals, courses and documents.',
      'Supervisor — everything an Employee can do, plus approving their team\'s leave and timesheets, assigning courses, raising job requisitions and running reports. tmPro makes someone a Supervisor automatically when their login is created if anyone reports to them.',
      'HR — manages people, employee records, leave settings, payroll, recruitment, training, documents and announcements.',
      'Admin — everything HR can do, plus organisation settings, branches, departments, designations and billing.',
    ],
    steps: [
      'To change a role: People → (person) → Permission → choose the Role → "Save". The person must already have a login. You cannot change your own role.',
      'Only an Admin can give someone the Admin role, or change an existing Admin\'s role, login email or password.',
    ],
    tags: ['permissions', 'access', 'manager', 'supervisor', 'admin', 'hr', 'role'],
  },
  {
    slug: 'country-customisation',
    category: 'Getting started',
    title: 'Using tmPro in your country',
    summary: 'How country-specific tax, statutory and leave rules work.',
    body: [
      'Payroll tax and statutory deductions are built in for each supported country and applied by each employee\'s country — for example PAYE, NAPSA and NHIMA in Zambia.',
      'Leave rules are set per country under Settings → Leave.',
      'Your organisation\'s currency, time zone and regulatory registration numbers are set under Settings → Organization.',
      'If your country isn\'t listed yet, or a rate has changed, email us@bitware.app — we add and update country rules for customers.',
    ],
    tags: ['country', 'localisation', 'localization', 'tax', 'statutory', 'currency', 'customisation', 'customization'],
  },

  // ---------------------------------------------------------------- Signing in
  {
    slug: 'sign-in',
    category: 'Signing in',
    title: 'How to sign in',
    summary: 'tmPro asks for your email first, then your password.',
    steps: [
      'Go to tmpro.bitware.app/login.',
      'Enter your work email and click "Continue".',
      'If your email is used at more than one organisation, choose the one you want.',
      'Enter your password and click "Sign in".',
    ],
    tip: 'You stay signed in for up to 12 hours. After that you\'ll be asked to sign in again.',
    tags: ['login', 'log in', 'signin', 'email', 'password'],
  },
  {
    slug: 'forgot-password',
    category: 'Signing in',
    title: 'I forgot my password',
    summary: 'Get a reset link from the sign-in page.',
    steps: [
      'Go to tmpro.bitware.app/login, enter your email and click "Continue".',
      'On the password screen, click "Forgot password?".',
      'Check your email for a reset link. It works once and expires after one hour.',
      'Open the link, enter your new password twice and click "Set new password".',
    ],
    tip: 'The link goes to your login email address. If it doesn\'t arrive, check your spam folder, or ask your Admin or HR team to send one from People → (your name) → Permission → "Reset password".',
    tags: ['reset', 'forgot', 'locked out', 'password', 'forgotten'],
  },
  {
    slug: 'change-password',
    category: 'Signing in',
    title: 'Change your password',
    summary: 'Change your own password at any time from the sidebar.',
    steps: [
      'Click your email address at the bottom of the left sidebar.',
      'Enter your current password, then your new password twice (at least 8 characters).',
      'Click "Save".',
    ],
    tip: 'If you were given a temporary password, tmPro asks you to choose your own the first time you sign in.',
    tags: ['password', 'security', 'temporary password'],
  },
  {
    slug: 'give-login',
    category: 'Signing in',
    title: 'Give an employee a login',
    summary: 'Create sign-in access for someone already in tmPro.',
    who: 'Admin, HR',
    steps: [
      'Open People → (person) → General Info and make sure their personal email is filled in. It becomes their login email.',
      'Go to the Permission tab and click "Generate Login".',
      'tmPro creates a unique temporary password, emails it to them, and shows it to you once so you can pass it on.',
      'The first time they sign in, they must choose their own password before they can use tmPro.',
    ],
    tip: 'To change someone\'s login email later, use Permission → Account email. Both the old and new addresses are notified.',
    tags: ['invite', 'account', 'access', 'login', 'new user'],
  },
  {
    slug: 'theme',
    category: 'Signing in',
    title: 'Switch between Classic and Midnight themes',
    summary: 'Choose between the two looks for tmPro. Midnight is the default.',
    steps: [
      'Use the theme switch at the bottom of the left sidebar. Your choice is remembered on that device.',
      'Midnight gives each card a tinted header band in the colour of that area of tmPro (for example cyan for Leave, orange for Payroll). Classic marks card titles with a short bar in the same colour.',
    ],
    tags: ['dark mode', 'appearance', 'theme', 'midnight'],
  },

  // ---------------------------------------------------------------- People
  {
    slug: 'contracts-gratuity',
    category: 'People',
    title: 'Record an employment contract and gratuity',
    summary: 'Contract types, renewals, and how fixed-term gratuity is worked out and paid.',
    who: 'Admin, HR',
    steps: [
      'Open the person → Job → Contract and click "New contract".',
      'Choose the contract type — Permanent (pensionable), Permanent (non-pensionable), Fixed-term, Temporary or Casual — and the start date. Fixed-term and temporary contracts need an end date.',
      'For a pensionable contract, name the pension scheme. For a fixed-term contract, set the gratuity rate: in Zambia a contract of 12 months or longer earns at least 25% (tmPro fills this in and won’t accept less); you can agree more, such as 30%, 35% or 40%.',
      'Add the probation end date and notice period if you track them. To renew, add a new contract starting the day after the old one ends — each contract keeps its own gratuity.',
    ],
    body: [
      'The contract in force decides the leave rules that apply (for example, Zambian annual leave excludes temporary and casual staff, and sick pay depends on whether the contract is 12 months or less).',
      'Gratuity = the rate × the last-drawn basic pay (no allowances, overtime or bonuses) × the months served. The Contract section shows what has built up so far, and Reports → "Gratuity liability" shows the total across the organisation.',
      'When a fixed-term contract ends — or the person leaves early — the next pay run pays the gratuity automatically. In Zambia the statutory 25% is paid tax-free and anything above 25% is added to gross pay and taxed through PAYE.',
    ],
    tags: ['contract', 'fixed-term', 'permanent', 'pensionable', 'casual', 'temporary', 'gratuity', 'renewal', 'probation'],
  },
  {
    slug: 'add-employee',
    category: 'People',
    title: 'Add an employee',
    summary: 'Create a new employee record.',
    who: 'Admin, HR',
    steps: [
      'Go to Settings → Employees and click "Add employee".',
      'Fill in their name, employee ID, country, branch, designation, department, section, direct manager ("Reports to"), employment type, source of hire and work phone.',
      'Click "Create employee".',
      'Open the person under People to add personal details, job and pay information on the General Info and Job tabs.',
    ],
    tip: 'If you\'ve reached your plan\'s employee limit, tmPro asks you to move to a larger size under Settings → Billing first.',
    tags: ['new employee', 'hire', 'create', 'staff'],
  },
  {
    slug: 'import-employees',
    category: 'People',
    title: 'Import employees from a CSV file',
    summary: 'Add many employees at once from a spreadsheet.',
    who: 'Admin, HR',
    steps: [
      'Go to Settings → Employees and click "Sample CSV" to download the template.',
      'Fill in one row per employee: firstName, lastName, employeeCode, jobTitle, countryCode, managerCode, sourceOfHire, workPhone, employmentType. You can also add branch, department, section and designation columns; these must match names already set up in Settings.',
      'employmentType must be FULL_TIME, PART_TIME, CONTRACT or INTERN.',
      'Save the file as CSV and click "Data Import (CSV)".',
      'tmPro tells you how many rows were imported and lists any rows it skipped, with the reason.',
    ],
    tags: ['csv', 'bulk', 'upload', 'spreadsheet', 'excel', 'import'],
  },
  {
    slug: 'employee-leaves',
    category: 'People',
    title: 'When an employee leaves the organisation',
    summary: 'Record a departure so payroll and your employee count update.',
    who: 'Admin, HR',
    steps: [
      'Open People → (person) → Job tab.',
      'In the Employee status card, add a new entry with status ALUMNI and the date they leave. Add a comment if you like.',
    ],
    body: [
      'From that date they can no longer sign in to tmPro — including any session they already have open. If you date it in the future, they keep access until then.',
      'Former staff (ALUMNI) no longer count towards your plan\'s employee limit, and payroll stops from the effective date. Their records are kept for your history.',
      'To restore access (for example if they return), add a new ACTIVE status entry.',
      'Use OFFBOARDING for people who are working their notice period, and ON LEAVE for extended absences.',
    ],
    tags: ['terminate', 'resign', 'offboard', 'alumni', 'former', 'deactivate', 'exit'],
  },
  {
    slug: 'org-chart',
    category: 'People',
    title: 'View or download the organisation chart',
    summary: 'The org chart is built from designations and reporting lines.',
    steps: [
      'Set who each designation reports to under Settings → Designations.',
      'Open Settings → Org Chart to see the chart.',
      'Click "Download PDF" to save or print it.',
    ],
    tags: ['org chart', 'hierarchy', 'structure', 'reporting lines', 'pdf'],
  },

  // ---------------------------------------------------------------- Leave
  {
    slug: 'request-leave',
    category: 'Leave',
    title: 'Request leave',
    summary: 'Apply for leave and see exactly how many days it will cost before you submit.',
    who: 'Everyone with an employee profile',
    steps: [
      'Go to Leave. Your balances are at the top.',
      'Under "Request leave", choose the type and your first and last day. Tick "Half day" for a half day at either end.',
      'tmPro shows a live check: how many working days it costs (weekends and public holidays are skipped), your balance before and after, and any rule it breaks.',
      'Add a reason and a supporting document if the type needs one, then click "Submit request". Your supervisor (and HR, if needed) is notified.',
    ],
    tip: 'You can cancel a request while it is pending, or an approved one before it starts. After it has started, ask HR.',
    tags: ['apply', 'holiday', 'annual leave', 'vacation', 'time off', 'half day', 'balance'],
  },
  {
    slug: 'approve-leave',
    category: 'Leave',
    title: 'Approve or decline leave',
    summary: 'Supervisors, HR and Admins decide requests from the Leave page.',
    who: 'Supervisor, HR, Admin',
    steps: [
      'Go to Leave. Requests waiting for you are under "Waiting for your approval".',
      'Add a comment if you like, then click "Approve" or "Decline". The employee is emailed.',
      'Some leave types need two steps (supervisor, then HR). After the supervisor approves, HR is notified.',
    ],
    body: [
      'tmPro re-checks the balance at the moment of approval, so leave can never be approved into a balance that has since been used.',
      'HR and Admins see every pending request; supervisors see their own team.',
    ],
    tags: ['approve', 'decline', 'reject', 'manager', 'team', 'approval'],
  },
  {
    slug: 'how-balances-work',
    category: 'Leave',
    title: 'How leave balances are calculated',
    summary: 'Accruals, yearly and monthly allowances, and what happens to unused days.',
    body: [
      'Annual leave accrues every month — in Zambia at least 2 days per month (Employment Code Act s.36) — credited on the last day of each month, pro-rated for a part month. It carries over and is paid out when someone leaves.',
      "Allowances such as compassionate leave (12 days a calendar year), family responsibility leave (7) and Mother's Day (1 each month) are granted in full at the start of the period and lapse at its end.",
      'Maternity and paternity leave are granted per birth; sick leave is tracked per illness with full-pay and half-pay periods.',
      'Every change to a balance is recorded with its date and reason — see People → (person) → Leave → Balance history.',
    ],
    tags: ['accrual', 'balance', 'carry over', 'entitlement', 'lapse', 'how'],
  },
  {
    slug: 'sick-leave',
    category: 'Leave',
    title: 'Sick leave and sick pay',
    summary: 'How tmPro works out full pay, half pay and unpaid sick days.',
    body: [
      'Zambia (s.38): on a contract of 12 months or less, 26 working days on full pay then 26 on half pay; on a longer contract, 3 months on full pay then 3 months on half pay.',
      'An absence that starts within 14 days of the last one continues the same illness (HR can change the 14 days in Settings → Leave → Processing).',
      'Half-pay and unpaid days are deducted automatically in payroll. After 6 months tmPro flags the person for a medical-discharge review.',
      'A medical certificate is required for more than one day off sick.',
    ],
    tags: ['sick', 'illness', 'medical', 'certificate', 'half pay', 'sick pay'],
  },
  {
    slug: 'family-leave',
    category: 'Leave',
    title: "Maternity, paternity and Mother's Day",
    summary: 'The family leave rules built into tmPro for Zambia.',
    body: [
      'Maternity: 14 weeks (98 calendar days), plus 4 weeks for a multiple birth, with full pay after 24 months of service. Enter the expected or actual delivery date when you apply.',
      'Paternity: 5 working days, taken within 7 days of the birth, after 12 months of service. Attach the birth record.',
      "Mother's Day: every female employee may take one day each month with no reason or certificate. It's approved automatically; unused days don't carry over.",
    ],
    tags: ['maternity', 'paternity', 'mothers day', "mother's day", 'birth', 'baby', 'twins'],
  },
  {
    slug: 'leave-settings',
    category: 'Leave',
    title: 'Set up leave policies',
    summary: 'Change entitlements, approval steps and rules — never below the legal minimum.',
    who: 'Admin, HR',
    steps: [
      'Go to Settings → Leave → Policies and choose the country.',
      'Click "Edit" on a leave type. Change the days, service requirements, carry-forward cap or approval steps.',
      'Choose the date the change takes effect and click "Save". Past balances keep the rule that applied at the time.',
    ],
    body: [
      'Zambian policies start from the Employment Code Act. You can make them more generous; going below the legal minimum needs a declared exemption with a reference (e.g. SI No. 48 of 2020).',
      'Use "Add a company leave type" for extras such as study leave.',
    ],
    tags: ['policy', 'entitlement', 'settings', 'leave types', 'configure', 'carry forward'],
  },
  {
    slug: 'opening-balances',
    category: 'Leave',
    title: 'Bring leave balances from your old system',
    summary: 'Load everyone’s balances once, when you start using tmPro.',
    who: 'Admin, HR',
    steps: [
      'Go to Settings → Leave → Opening balances.',
      'Choose the cut-over date — the last day your old records are complete to — and click "Download template".',
      'Fill in each person’s annual leave balance and what they have already used of this year’s allowances (and any open sick leave). Leave rows blank to skip them.',
      'Upload the file and click "Upload & check". Fix any rows marked in red and upload again.',
      'Click "Post opening balances". From the cut-over onwards tmPro accrues leave itself.',
    ],
    tip: 'Posted a mistake? Adjust the individual balance, or reverse the whole batch and upload again.',
    tags: ['import', 'migration', 'opening balance', 'brought forward', 'csv', 'cut-over', 'onboarding'],
  },
  {
    slug: 'adjust-balance',
    category: 'Leave',
    title: 'Adjust someone’s leave balance',
    summary: 'Add or remove days with a reason — every adjustment is recorded.',
    who: 'Admin, HR',
    steps: [
      'Open People → (person) → Leave and click "Adjust balance".',
      'Choose the leave type, + or − and the number of days, the effective date, a reason and a note. Click "Save adjustment".',
      'To undo it, click "Reverse" next to it in the Balance history. Adjustments are never edited or deleted.',
    ],
    tags: ['adjust', 'correction', 'add days', 'remove days', 'balance'],
  },
  {
    slug: 'holidays-work-weeks',
    category: 'Leave',
    title: 'Public holidays and work weeks',
    summary: 'Which days count as leave days.',
    who: 'Admin, HR',
    body: [
      "Zambia's and Malawi's public holidays are built in — including Zambia's rule that a Sunday holiday is observed on the Monday, Malawi's rule that a weekend holiday moves to the next working day, and gazetted one-offs such as election days. Add company closures under Settings → Leave → Public holidays.",
      'A work week says which days count. Most people use the organisation default (Monday–Friday); set a different one — for example Saturday as a half day — under Settings → Leave → Work weeks, then choose it on the person’s Leave tab (Leave profile).',
    ],
    tags: ['public holiday', 'holiday calendar', 'work week', 'saturday', 'schedule', 'working days'],
  },
  {
    slug: 'leave-when-leaving',
    category: 'Leave',
    title: 'What happens to leave when someone leaves',
    summary: 'Unused annual leave is paid out automatically.',
    body: [
      'When someone’s status becomes Alumni, tmPro works out their annual leave up to their last day and adds a "Leave pay on termination" line to the next pay run (Zambia s.36(5), Malawi s.45).',
      'The daily rate is monthly basic pay ÷ 26 by default — change it under Settings → Leave → Processing.',
      'Reports → "Leave liability" shows what untaken leave is worth across the organisation today.',
    ],
    tags: ['termination', 'resign', 'payout', 'final pay', 'liability', 'encashment'],
  },
  {
    slug: 'leave-malawi',
    category: 'Leave',
    title: 'Leave rules for employees in Malawi',
    summary: 'How tmPro applies the Employment Act 2000 (as amended in 2021).',
    body: [
      'Annual leave: 15 working days a year on a 5- or 5½-day week, 18 on a 6-day week, building up monthly (s.44). It should be taken within 6 months of falling due — tmPro flags overdue leave on the person’s leave card and in Reports → "Overdue annual leave", but never forfeits it. Unused leave is paid out when someone leaves (s.45).',
      'Sick leave: unpaid in the first 12 months of service. After that, each service year gives 4 weeks on full pay and then 8 weeks on half pay (s.46), counted in working days for the person’s week. A medical certificate is required.',
      'Maternity leave: 8 weeks (56 calendar days) on full pay, once every 3 years (s.47). Paternity leave: 2 weeks (14 calendar days) on full pay, once every 3 years (s.47A, added in 2021). A second request inside the 3 years shows as unpaid, so HR can decide.',
      'Compassionate, family responsibility, study and wedding leave are not in the Act. tmPro sets each to 5 working days a year as a company default — change them under Settings → Leave → Policies (Malawi).',
      'Public holidays falling on a Saturday or Sunday move to the next working day. Eid al-Fitr depends on the moon: add it each year under Settings → Leave → Public holidays once it is announced.',
    ],
    tags: ['malawi', 'employment act', 'paternity', 'maternity', 'sick leave', 'overdue', 'annual leave'],
  },
  {
    slug: 'leave-new-zealand',
    category: 'Leave',
    title: 'Leave rules for employees in New Zealand',
    summary: 'How tmPro applies the Holidays Act 2003.',
    body: [
      'Annual holidays: 4 weeks after each 12 months of continuous employment, granted on the work anniversary in working days for the person’s week (20 days on a 5-day week, 12 on a 3-day week). Leave in advance can be allowed with “May go negative by” in Settings → Leave → Policies. Someone who leaves before their first anniversary is paid 8% of gross earnings — work that out in payroll.',
      'Sick leave: 10 days after 6 months, then 10 more every 12 months, carrying over to a maximum of 20. Proof can be asked for after 3 or more consecutive days. It is not paid out on leaving.',
      'Bereavement leave: 3 days for a close family member or after a miscarriage or stillbirth, 1 day for anyone else, after 6 months. Family violence leave: 10 days a year after 6 months; no reason is asked and requests go to HR only.',
      'Parental leave (up to 26 weeks) and partner’s leave (up to 2 weeks) are unpaid by the employer — the government pays parental leave payments through Inland Revenue.',
      'Public holidays, including Matariki, are built in, and New Year, 2 January, Waitangi Day, ANZAC Day, Christmas and Boxing Day are Mondayised when they fall on a weekend. Add your regional anniversary day under Settings → Leave → Public holidays.',
      'The Employment Leave Bill will replace the Holidays Act (targeted for 2028). tmPro will add its rules as a new dated version when it passes.',
    ],
    tags: ['new zealand', 'nz', 'holidays act', 'sick leave', 'bereavement', 'matariki', 'annual holidays', 'family violence'],
  },
  {
    slug: 'leave-australia',
    category: 'Leave',
    title: 'Leave rules for employees in Australia',
    summary: 'How tmPro applies the National Employment Standards.',
    body: [
      'Annual leave: 4 weeks a year, accruing monthly and carrying over, paid out on termination. Personal/carer’s leave: 2 weeks a year (10 days full-time), accruing and carrying over, not paid out. Both are pro rata for part-timers and don’t apply to casual employees.',
      'Compassionate leave: 2 days per occasion. Family and domestic violence leave: 10 days each year from the start, for everyone including casuals; no reason is asked and requests go to HR only.',
      'Parental leave: up to 12 months unpaid after 12 months of service. Parental Leave Pay (26 weeks from 1 July 2026) comes from the government, not the employer.',
      'Awards and agreements can give more (a fifth week for shift workers, leave loading) — change the policies under Settings → Leave → Policies. Long service leave is set by each state and isn’t included yet.',
      'The public holidays common to every state are built in. Add your state’s own holidays (Labour Day, Melbourne Cup and so on) under Settings → Leave → Public holidays.',
    ],
    tags: ['australia', 'au', 'fair work', 'nes', 'personal leave', 'carers leave', 'annual leave', 'domestic violence'],
  },
  {
    slug: 'leave-south-africa',
    category: 'Leave',
    title: 'Leave rules for employees in South Africa',
    summary: 'How tmPro applies the Basic Conditions of Employment Act.',
    body: [
      'Annual leave: 21 consecutive days a year — 15 working days on a 5-day week, 18 on a 6-day week, 9 on a 3-day week — building up monthly (s.20). It should be taken within 6 months of the end of the leave cycle; tmPro flags overdue leave but never forfeits it. Unused leave is paid out on termination.',
      'Sick leave: in each 36-month cycle, the days normally worked in 6 weeks (30 on a 5-day week). In the first 6 months only 1 paid day is earned for every 26 days worked (s.22). A medical certificate can be required for more than 2 consecutive days.',
      'Family responsibility leave: 3 paid days a year after 4 months, for people who work at least 4 days a week (s.27).',
      'Parental leave follows the Constitutional Court’s Van Wyk order (3 October 2025): 4 months for a sole employed parent, or 4 months and 10 days shared between two employed parents. It is unpaid by the employer (UIF benefits may apply). tmPro allows up to 132 days per birth — check how the parents are sharing it when approving.',
      'Public holidays falling on a Sunday move to the Monday.',
    ],
    tags: ['south africa', 'za', 'bcea', 'sick leave cycle', 'family responsibility', 'parental leave', 'van wyk', 'annual leave'],
  },
  {
    slug: 'leave-zimbabwe',
    category: 'Leave',
    title: 'Leave rules for employees in Zimbabwe',
    summary: 'How tmPro applies the Labour Act [Chapter 28:01].',
    body: [
      'Vacation leave: 30 calendar days a year (2.5 a month), counted in calendar days — weekends and public holidays inside a leave period count as leave days (s.14A). It builds up to a maximum of 90 days and then stops until some is taken. Unused leave is paid out on termination.',
      'Sick leave: up to 90 days on full pay in each year of service, then up to 90 more on half pay, with a medical certificate (s.14).',
      'Maternity leave: 98 days on full pay. Since the Labour Amendment Act 2023 there is no minimum service and no limit on how often it can be taken (s.18).',
      'Special leave: up to 12 paid days a calendar year, for example for a funeral or a court subpoena (s.14B).',
      'Public holidays falling on a Sunday move to the Monday. Heroes’ Day and Defence Forces Day are the second Monday and Tuesday of August.',
    ],
    tags: ['zimbabwe', 'zw', 'labour act', 'vacation leave', 'special leave', 'maternity', 'sick leave'],
  },

  // ---------------------------------------------------------------- Timesheets
  {
    slug: 'submit-timesheet',
    category: 'Timesheets',
    title: 'Submit a timesheet',
    summary: 'Record the hours you worked.',
    who: 'Employees with timesheets turned on',
    steps: [
      'Go to Timesheets → My Timesheets.',
      'Click "Add Timesheet" for a single day or "Add Weekly Timesheet" for a week.',
      'Enter the date, start and end times, breaks, work site, position, work type and any notes, then save.',
    ],
    tip: 'You can edit or delete an entry until it has been approved. If you don\'t see Timesheets, ask HR to turn it on for you in Settings → Employees.',
    tags: ['hours', 'time', 'clock', 'weekly'],
  },
  {
    slug: 'approve-timesheets',
    category: 'Timesheets',
    title: 'Approve timesheets',
    summary: 'Review and approve submitted hours.',
    who: 'Supervisor, HR, Admin',
    steps: [
      'Go to Timesheets → Review. Supervisors see their team; Admin and HR see everyone.',
      'Click "Approve" or "Decline". The employee is notified by email.',
    ],
    tags: ['approve', 'hours', 'review'],
  },

  // ---------------------------------------------------------------- Payroll
  {
    slug: 'set-pay',
    category: 'Payroll',
    title: 'Set an employee\'s pay',
    summary: 'Record salary, pay type and allowances.',
    who: 'Admin, HR',
    steps: [
      'Open People → (person) → Job → Compensation.',
      'Enter the basic pay rate, pay type, hours per week and any allowances (housing, transport, meal, other).',
      'Save. Changes are kept as a dated history.',
    ],
    tags: ['salary', 'wage', 'compensation', 'allowance', 'pay rate'],
  },
  {
    slug: 'run-payroll',
    category: 'Payroll',
    title: 'Run payroll',
    summary: 'Calculate pay and statutory deductions for a period.',
    who: 'Admin, HR',
    steps: [
      'Go to Payroll → Pay Runs.',
      'Enter the period start and end dates and choose the country.',
      'Click "Run payroll". Every employee in that country is included, pro-rated for joiners, leavers and status changes.',
      'Click the run to check each employee\'s payslip before paying.',
      'Use "Edit" to change a run\'s status to PAID once staff have been paid.',
    ],
    tip: 'To recalculate a run after changing someone\'s pay, delete the run and run it again.',
    tags: ['payroll', 'pay run', 'salaries', 'paye', 'tax', 'deductions'],
  },
  {
    slug: 'payroll-countries',
    category: 'Payroll',
    title: 'What each country\'s payroll works out',
    summary: 'The tax and contributions tmPro calculates for Zambia, Malawi, New Zealand, Australia, South Africa and Zimbabwe.',
    who: 'Admin, HR',
    steps: [
      'Zambia: PAYE on monthly bands, NAPSA 5% (capped) and NHI 1% of basic pay.',
      'Malawi (MWK): PAYE 0% to K170,000, then 30%, 35% and 40% above K10 million a month; pension 5% of basic pay from the employee. The employer\'s 10% is shown on the payslip.',
      'New Zealand (NZD): PAYE (tax code M), ACC earners\' levy (1.75% up to $156,641 a year from 1 April 2026) and KiwiSaver at the employee\'s rate, 3.5% by default. The employer\'s KiwiSaver is shown.',
      'Australia (AUD): PAYG for a resident claiming the tax-free threshold, with the low income tax offset (15% bottom rate from 1 July 2026), plus the 2% Medicare levy. Super guarantee of 12% is shown, not deducted.',
      'South Africa (ZAR): PAYE on the SARS tables for the tax year (from 1 March), less the primary rebate; UIF 1% up to R17,712 a month. Employer UIF and SDL are shown.',
      'Zimbabwe (USD): PAYE on the ZIMRA USD monthly bands after NSSA, plus the 3% AIDS levy; NSSA 4.5% up to US$700 a month. Employer NSSA is shown.',
    ],
    tip: 'Tax is worked out on the whole period\'s pay, including taxable additions such as bonuses. Not handled yet: tax credits, age rebates, student loans and HELP debts, medical aid credits. Enter these as additions or deductions. Tell us at us@bitware.app if a rate changes.',
    tags: ['paye', 'payg', 'kiwisaver', 'acc', 'uif', 'sdl', 'nssa', 'aids levy', 'medicare', 'super', 'superannuation', 'pension', 'malawi', 'australia', 'new zealand', 'south africa', 'zimbabwe', 'tax'],
  },
  {
    slug: 'additions-deductions',
    category: 'Payroll',
    title: 'Add a bonus or a deduction',
    summary: 'Schedule one-off or repeating additions and deductions.',
    who: 'Admin, HR',
    steps: [
      'Go to Payroll → Additions & Deductions.',
      'Choose Addition (for example a bonus) or Deduction (for example an advance repayment), and enter a label and the amount per pay run.',
      'Set how many pay runs it applies over, choose the employees and click "Schedule".',
    ],
    tags: ['bonus', 'deduction', 'advance', 'loan', 'overtime'],
  },
  {
    slug: 'statutory-returns',
    category: 'Payroll',
    title: 'Generate statutory returns',
    summary: 'Produce tax, pension and health-insurance return files.',
    who: 'Admin, HR',
    steps: [
      'Go to Payroll → Regulatory Submission.',
      'Choose the return (for example PAYE, NAPSA or NHIMA), month and year.',
      'Click "Generate Return File" or "Export to CSV", check it, and submit it to the authority.',
    ],
    tip: 'Always check returns before filing. Tell us at us@bitware.app if a statutory rate has changed.',
    tags: ['paye', 'napsa', 'nhima', 'return', 'tax', 'pension', 'superannuation', 'zra', 'export'],
  },
  {
    slug: 'payslips',
    category: 'Payroll',
    title: 'View and print your payslip',
    summary: 'Find your payslip for any month.',
    who: 'Employee, Supervisor',
    steps: ['Go to Payroll → "Your payslips".', 'Choose the month and year and click "View Payslip".', 'Click "Print" to print or save it as a PDF.'],
    tags: ['payslip', 'pay slip', 'salary slip', 'print', 'pdf'],
  },

  // ---------------------------------------------------------------- Recruitment
  {
    slug: 'raise-requisition',
    category: 'Recruitment',
    title: 'Raise and approve a job requisition',
    summary: 'Request a new hire and get it approved.',
    who: 'Supervisor, HR, Admin (approval: HR, Admin)',
    steps: [
      'Go to Recruitment → Requisitions and click "Raise requisition".',
      'Enter the role title, department, headcount, target start date, employment type and location.',
      'HR or Admin clicks "Approve".',
    ],
    tags: ['vacancy', 'hiring', 'job', 'requisition', 'headcount'],
  },
  {
    slug: 'publish-job',
    category: 'Recruitment',
    title: 'Advertise a job on your careers page',
    summary: 'Publish an approved requisition so people can apply online.',
    who: 'HR, Admin',
    steps: [
      'Open the requisition and click "Public listing".',
      'Describe the role: your role, what you\'ll do, what you\'ll bring, what you\'ll get, why us and the required skills. Click "Save listing".',
      'Once the requisition is approved, the job appears on your public careers page and in the job search at tmpro.bitware.app/careers.',
    ],
    tags: ['careers', 'job ad', 'advert', 'publish', 'listing', 'vacancy'],
  },
  {
    slug: 'review-applications',
    category: 'Recruitment',
    title: 'Review job applications',
    summary: 'Read CVs and cover letters from applicants.',
    who: 'HR, Admin',
    steps: ['Go to Recruitment → Application Review.', 'Open an application to see the candidate\'s details, then click "View CV" or "View Cover Letter".'],
    tip: 'Applicants don\'t need an account. They apply directly from your careers page and upload a CV of up to 2 MB.',
    tags: ['applicants', 'candidates', 'cv', 'resume', 'applications'],
  },

  // ---------------------------------------------------------------- Performance & training
  {
    slug: 'goals',
    category: 'Performance & training',
    title: 'Set and update your goals',
    summary: 'Track your own performance goals.',
    steps: ['Go to Performance.', 'Add a goal under "Your goals".', 'Click a goal to move it from Not started to In progress to Completed.'],
    tags: ['goals', 'objectives', 'okr', 'performance'],
  },
  {
    slug: 'performance-review',
    category: 'Performance & training',
    title: 'Record a performance review',
    summary: 'Rate an employee and keep review history.',
    who: 'Admin, HR',
    steps: [
      'Open People → (person) → Performance.',
      'Add a review: reviewer, date, and ratings from 1 to 5 for attendance, communication, dependability, job knowledge and work quality.',
      'tmPro works out the average score. You can also add comments and goals for the employee here.',
    ],
    tags: ['appraisal', 'review', 'rating', 'evaluation'],
  },
  {
    slug: 'training-courses',
    category: 'Performance & training',
    title: 'Create, assign and complete training courses',
    summary: 'Build a course library and track completion.',
    who: 'Create: Admin, HR · Assign: Supervisor, HR, Admin',
    steps: [
      'Settings → Training → "Add course": enter a title and course link (YouTube videos play inside tmPro). Add an image and quiz if you like, then "Publish" it.',
      'Training → Assign Courses: choose the course and the people.',
      'Employees open Training → My Courses, then "Take quiz" or "Mark as complete".',
    ],
    tags: ['lms', 'learning', 'course', 'quiz', 'training'],
  },

  // ---------------------------------------------------------------- Documents & announcements
  {
    slug: 'documents',
    category: 'Documents & announcements',
    title: 'Upload and find documents',
    summary: 'Keep contracts, IDs and other files with the employee record.',
    body: [
      'Employees upload their own files under Documents → My Documents, choosing Contract, ID or Other. Files can be PDF or images up to 2 MB.',
      'Admin and HR see every document in the organisation, grouped by type, and can upload documents on a person\'s profile (People → person → Documents).',
      'Reports → "Contract copies not on file" and "ID copies not on file" show who is missing documents.',
    ],
    tags: ['upload', 'contract', 'id', 'file', 'pdf', 'documents'],
  },
  {
    slug: 'announcements',
    category: 'Documents & announcements',
    title: 'Send an announcement',
    summary: 'Share news with everyone or a department.',
    who: 'Admin, HR',
    steps: [
      'Go to Settings → Announcements → New announcement.',
      'Enter a title and message and choose the audience: the entire organisation, a department or a section.',
      'Click "Send". It\'s emailed to the audience and shown on their Dashboard.',
    ],
    tags: ['news', 'broadcast', 'message', 'notice', 'email'],
  },
  {
    slug: 'reports',
    category: 'Documents & announcements',
    title: 'Run a report',
    summary: 'See leave, performance and compliance reports.',
    who: 'Admin, HR, Supervisor',
    steps: ['Go to Reports.', 'Choose a report and a From/To date range, then click "Run report".'],
    body: [
      'Available reports: leave days accumulated, performance goals set, performance appraisals conducted, unresponded requests per supervisor, contract copies not on file, and ID copies not on file.',
    ],
    tags: ['reports', 'analytics', 'compliance'],
  },

  // ---------------------------------------------------------------- Billing
  {
    slug: 'trial',
    category: 'Billing & plans',
    title: 'How the free trial works',
    summary: 'Seven days free, then monthly billing unless you cancel.',
    body: [
      'Every new subscription starts with a 7-day free trial. A Visa or Mastercard credit or debit card is needed to start, but nothing is charged during the trial.',
      'Your card is charged the monthly price when the trial ends. Cancel before then under Settings → Billing → "Manage payment & invoices" and you won\'t be charged.',
    ],
    tags: ['trial', 'free', 'card', 'charge'],
  },
  {
    slug: 'change-plan',
    category: 'Billing & plans',
    title: 'Change your plan or company size',
    summary: 'Move between Core, Growth and Pro, or change your employee band.',
    who: 'Admin',
    steps: [
      'Go to Settings → Billing.',
      'Choose a company size, then click Upgrade, Downgrade or Switch on the plan you want.',
      'Click "Confirm change".',
    ],
    body: [
      'Upgrades take effect immediately, and the prorated difference for the rest of the month is charged to your card today.',
      'Downgrades take effect immediately and the lower price applies from your next invoice. Your data in any removed modules is kept.',
      'You can\'t choose a size smaller than your current number of employees. More than 200 employees? Email us@bitware.app for custom pricing.',
    ],
    tags: ['upgrade', 'downgrade', 'plan', 'band', 'size', 'seats', 'employees limit'],
  },
  {
    slug: 'update-card',
    category: 'Billing & plans',
    title: 'Update your card or download invoices',
    summary: 'Manage payment details on Stripe\'s secure billing page.',
    who: 'Admin',
    steps: [
      'Go to Settings → Billing and click "Manage payment & invoices".',
      'On the secure Stripe page you can change your card, download invoices and receipts, and update your billing details.',
    ],
    tags: ['card', 'visa', 'mastercard', 'invoice', 'receipt', 'payment method'],
  },
  {
    slug: 'payment-failed',
    category: 'Billing & plans',
    title: 'My payment failed',
    summary: 'What happens when a card payment doesn\'t go through.',
    body: [
      'A red banner appears in tmPro and the card is retried automatically over the next few days. You can keep using tmPro meanwhile.',
      'To fix it, go to Settings → Billing → "Manage payment & invoices" and update your card. Check with your bank that international (USD) online payments are allowed.',
      'If payment still fails after the retries, the subscription ends and sign-in is paused until it\'s paid. Your data is kept for 90 days.',
    ],
    tags: ['declined', 'failed', 'past due', 'overdue', 'card', 'suspended'],
  },
  {
    slug: 'cancel',
    category: 'Billing & plans',
    title: 'Cancel your subscription',
    summary: 'Stop renewal at the end of the paid month.',
    who: 'Admin',
    steps: ['Go to Settings → Billing → "Manage payment & invoices".', 'Click "Cancel subscription" on the Stripe page and confirm.'],
    body: [
      'You keep access until the end of the month you\'ve paid for and won\'t be charged again. We keep your data for 90 days in case you come back or want a copy; after that it\'s deleted.',
      'Before cancelling, download a copy of your data from Settings → Organization → "Export all data".',
    ],
    tags: ['cancel', 'stop', 'close account', 'unsubscribe', 'refund'],
  },
  {
    slug: 'currency',
    category: 'Billing & plans',
    title: 'Which currency will I be charged in?',
    summary: 'Prices are charged in US dollars.',
    body: [
      'tmPro prices are set and charged in US dollars (USD). The local-currency amounts on the pricing page are estimates to help you compare.',
      'Your bank converts the charge to your card\'s currency and may add a foreign-transaction fee.',
    ],
    tags: ['usd', 'currency', 'kwacha', 'rand', 'exchange rate', 'conversion'],
  },

  // ---------------------------------------------------------------- Privacy & security
  {
    slug: 'data-security',
    category: 'Privacy & security',
    title: 'How tmPro keeps your data safe',
    summary: 'The main security measures protecting your workspace.',
    body: [
      'All connections are encrypted (HTTPS), and data is stored on encrypted AWS infrastructure.',
      'Each organisation\'s data is kept separate: every request is limited to your organisation, and database row-level security adds a second barrier.',
      'Passwords are stored only as one-way hashes. Every new login gets its own temporary password that must be changed at first sign-in. Sign-ins expire after 12 hours.',
      'When someone is marked as having left (Alumni), they can no longer sign in.',
      'Card payments are handled entirely by Stripe; tmPro never sees or stores card numbers.',
    ],
    tip: 'Read the full Privacy Policy at tmpro.bitware.app/privacy-policy.',
    tags: ['security', 'encryption', 'privacy', 'gdpr', 'safe', 'data protection'],
  },
  {
    slug: 'export-data',
    category: 'Privacy & security',
    title: 'Export all your organisation\'s data',
    summary: 'Download everything in your workspace as spreadsheets in a ZIP file.',
    who: 'Admin',
    steps: [
      'Go to Settings → Organization.',
      'Under "Export all data", click "Export all data".',
      'A ZIP file downloads with one CSV spreadsheet per type of record (employees, leave, payroll and so on) and a files folder with uploaded documents, photos and CVs.',
    ],
    tip: 'The export contains personal and pay information — store it securely. Passwords are never included.',
    tags: ['export', 'download', 'backup', 'csv', 'zip', 'data', 'migrate'],
  },
  {
    slug: 'data-request',
    category: 'Privacy & security',
    title: 'Request a copy or deletion of your data',
    summary: 'How organisations and individuals can make privacy requests.',
    body: [
      'Organisations: an Admin can download a full copy at any time from Settings → Organization → "Export all data". To have your workspace deleted, email us@bitware.app from your Admin\'s address.',
      'Employees and applicants: your employer controls your records, so contact your HR team first. They can view and correct your information in tmPro, and we\'ll help them with anything else.',
    ],
    tags: ['export', 'delete', 'privacy', 'personal information', 'access request'],
  },
];
